name: Modifyworld
main: ru.tehkode.modifyworld.bukkit.Modifyworld
soft-depend: [ PermissionsEx, Vault ]
version: "${project.version}"
author: t3hk0d3
website: www.bukkit.org
description: World modification permission ruleset
