name: Modifyworld
main: ru.tehkode.modifyworld.bukkit.Modifyworld
soft-depend: [ PermissionsEx ]
version: 1.19.3
author: t3hk0d3
website: www.bukkit.org
description: World modification permission ruleset
